### ISSUE TITLE
Разбить исходники на папки и сделать разные executable при помощи Cmake

### ISSUE THREAD

**Issue by benzlokzik** [error1001es/PP_CPP#1]
Пришел потоксичить, чтобы всё было окей к завтрашнему утру. Разбей всё в папки и полинкуй их через `cmakelists.txt` и сделай там `add_executable()`. 🥸

**Comment by error1001es** [comment]
я удалю исходники после того как сдам...

**Comment by benzlokzik** [comment]
Понял, незапланировано. Закрываю.
